### PR TITLE
fix: fix condition to use "--gpus all" option

### PR DESCRIPTION
**Pull request by raucha**
### Fix applied

**If your pull request is a bug fix, delete this line and all the below lines. **

**If your pull request is a feature implementation, delete this line and all the above lines. **

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@raucha Thank you for the fix! However, you must sign your commits for us to accept them. Please see the "Details" link next to the DCO check below.

**Comment by raucha** [comment]
Uhh, i could fix by following DCO message, but i cant push.(Error 403).
Im going to reopen pull request.

**Review by JWhitleyWork — APPROVED** [review]
Looks good. Thanks! I'll merge when CI is finished.

**Comment by raucha** [comment]
Thank you!!

**Comment by JWhitleyWork** [comment]
@raucha I just realized that your sign-off signature is "Your Name <yourname@example.com>". I didn't catch it early enough to fix it on this merge but you must fix this if you intend to submit any further changes. It must be your actual name and your email address.

**Comment by raucha** [comment]
@JWhitleyWork 
Thanks for pointing that out.
In first , i tried to actual name and email, but they have been rejected by DCO.
In honest, i dont know why "Your Name yourname@example.com" was accepted.

**Pull request merged**
